#!/usr/bin/with-contenv bash

# copy config
if [ ! -f /config/config.yml ]; then
  echo "**** Config file not found, copying sample config ****"
  cp /app/ac2mqtt/settings/config_sample.yml /config/config.yml
else
  echo "**** Config file exists already ****"
fi

# update app
currentVersion=$(cat /app/ac2mqtt/version.txt)
LATEST_RELEASE=$(curl -sX GET "https://api.github.com/repos/liaan/broadlink_ac_mqtt/releases/latest"  | jq -r '. | .tag_name')

if [ ${LATEST_RELEASE} != ${currentVersion} ]; then
   echo "**** Newer version found. Grabbing latest code ****"
   curl -o /tmp/ac2mqtt.tar.gz -L "https://github.com/liaan/broadlink_ac_mqtt/archive/${LATEST_RELEASE}.tar.gz"
   tar xf /tmp/ac2mqtt.tar.gz -C /app/ac2mqtt --strip-components=1
   # hard code version 
   echo "**** Updating versions ****"
   echo ${LATEST_RELEASE} > /app/ac2mqtt/version.txt
else
   echo "**** Already at latest version ****"
fi


# permissions
chown abc:abc -R \
	/config \
	/app